formatter: markdown table

header-from: docs/header.md

sections:
  show:
    - header
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "vpc" {
    source = "github.com/n2solutionsio/terraform-aws-vpc"

    vpc_name = "my-vpc"
    vpc_cidr = "10.0.0.0/16"

    enable_private_subnets = true
    private_subnet_cidrs   = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: replace

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  escape: true
  indent: 2
  required: true
  type: true
